### ISSUE TITLE
You might want to add `reversed` attribute to <ol> that lists the articles

### ISSUE THREAD

**Issue by simevidas** [freddyb/homepage#172]
It makes more sense if newer articles have a larger ordinal number. 

    <ol reversed>

<img width="968" alt="Screenshot 2024-02-02 at 18 47 53" src="https://github.com/freddyb/homepage/assets/716405/2e974469-1fb9-4cf6-8cd5-2bb0304fcdab">

**Comment by freddyb** [comment]
<3 fixed
